stages:
  download:
    cmd: python3.12 -m model_training.dataset download
    outs:
    - data/raw/restaurant_sentiment.csv
  prepare:
    cmd: python3.12 -m model_training.dataset main
    deps:
    - data/raw/restaurant_sentiment.csv
    - model_training/dataset.py
    outs:
    - data/processed/dataset.csv
    params:
    - prepare.seed
  train:
    cmd: python3.12 -m model_training.pipeline
    deps:
    - data/processed/dataset.csv
    - model_training/pipeline.py
    params:
    - train.n_estimators
    - train.seed
    outs:
    - models/sentiment_model_v1.0.0.pkl
    metrics:
    - metrics/train_metrics.json:
        cache: true
