name: Lint and Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preprocess dataset
        run: |
          python -m model_training.dataset main


      - name: Run tests with coverage
        run: |
          pytest --cov=model_training --cov-report=xml --cov-report=term tests/

      - name: Run pylint
        run: |
          pylint src/ model_training/

      - name: Install pybadges
        run: pip install pybadges

      - name: Generate pylint badge
        run: |
          SCORE=$(pylint model_training/ src/ | tee pylint_output.txt | grep 'Your code has been rated at' | sed -E 's/.*rated at ([0-9\.]+)\/10.*/\1/')
          echo "Pylint score is $SCORE"
          mkdir -p badges
          python -m pybadges --left-text="pylint" --right-text="$SCORE/10" --right-color="green" > badges/pylint.svg

      - name: Commit and push badge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git pull origin ${{ github.ref_name }} --rebase
          git add badges/pylint.svg
          git commit -m "Auto-update pylint badge" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        

