name: Lint and Test

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preprocess dataset
        run: |
          python -m model_training.dataset main


      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term tests/

      - name: Run pylint
        run: |
          pylint src/ model_training/

      - name: Install pybadges
        run: pip install pybadges

      - name: Generate pylint badge
        run: |
          SCORE=$(pylint model_training/ src/ | tee pylint_output.txt | grep 'Your code has been rated at' | sed -E 's/.*rated at ([0-9\.]+)\/10.*/\1/')
          echo "Pylint score is $SCORE"
          mkdir -p badges
          python -m pybadges --left-text="pylint" --right-text="$SCORE/10" --right-color="green" > badges/pylint.svg

      - name: Generate test adequacy badge
        run: |
          CATEGORIES_COVERED=3  # update to 4 if you add monitoring
          ADEQUACY_SCORE=$(( CATEGORIES_COVERED * 100 / 4 ))
          echo "Adequacy score is $ADEQUACY_SCORE%"
          mkdir -p badges
          python -m pybadges --left-text="adequacy" --right-text="$ADEQUACY_SCORE%" --right-color="orange" > badges/adequacy.svg

      - name: Generate test coverage badge
        run: |
          COVERAGE=$(grep -Po 'line-rate="\K[\d.]+' coverage.xml | awk '{ printf("%.0f", $1 * 100) }')
          echo "Coverage is $COVERAGE%"
          mkdir -p badges
          python -m pybadges --left-text="coverage" --right-text="$COVERAGE%" --right-color="blue" > badges/coverage.svg


      - name: Commit and push badge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add badges/pylint.svg badges/coverage.svg badges/adequacy.svg
          git commit -m "Auto-update pylint badge" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        

