name: Lint and Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=model_training --cov-report=xml --cov-report=term tests/

      - name: Run pylint
        run: |
          pylint src/ model_training/

      - name: Install pybadges
        run: pip install pybadges

      - name: Generate pylint badge
        run: |
          SCORE=$(pylint src/ model_training/ | tee pylint_output.txt | grep 'Your code has been rated at' | sed -E 's/.*rated at ([0-9\.]+)\/10.*/\1/')
          echo "Pylint score is $SCORE"
          mkdir -p badges
          pybadges --left-text="pylint" --right-text="$SCORE/10" --right-color="green" > badges/pylint.svg

      - name: Commit badge to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add badges/pylint.svg
          git commit -m "Update pylint badge"
          git push
