name: Train and Save Model

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  train-model:
    runs-on: ubuntu-24.04
    env:
      VERSION: ${GITHUB_REF:11}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.9'

    - name: Install dependencies
      run: pip install -r requirements.txt


    - name: Train model and save artifact
      run: python src/train.py ${{env.VERSION}}


    - name: Create Release
      uses: softprops/action-gh-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{secrets.RELEASE_SECRET}}
      with:
        name: Model Release v${{env.VERSION}}
        files: ./models/sentiment_model_v${{env.VERSION}}.pkl
        draft: false
        prerelease: false

