name: Train and Save Model

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  train-model:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.9-slim'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Parse version info from tag
      run: |
        VERSION=${GITHUB_REF:11}

    - name: Train model and save artifact
      run: python train.py VERSION


    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: |
          *.joblib
          *.pkl

